eval_height: &eval_height 120
eval_width: &eval_width 120

# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  save_interval: 20
  eval_during_train: True
  eval_interval: 1
  epochs: 120
  print_batch_step: 10
  use_visualdl: True
  
  # used for static mode and model export
  image_shape: [3, *eval_height, *eval_width]
  save_inference_dir: ./inference
  best_model: ./output/MobileNetV3_small_x1_25/best_model

# model architecture
Arch:
  name: HRNet_W18_C
  class_num: 12
  pretrained: True
  use_ssld: True
  input_channel: 3
 
# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
    - BCELoss:
        weight: null
  Eval:
    - CELoss:
        weight: 1.0
    - BCELoss:
        weight: null


Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Piecewise
    learning_rate: 0.01
    decay_epochs: [30, 60, 90]
    values: [0.1, 0.01, 0.001, 0.0001]
  regularizer:
    name: 'L2'
    coeff: 0.0001


DataLoader:
  Train:
    dataset:
      name: MVTecDataset2
      dataset_path: "/home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3"
      kind: 'train'
      size: 128
      random_crop: False
      interpolation: bicubic
      aug_flip: True
      aug_rotate90: True
      aug_scaleRotate: False
      aug_brightness_contrast: True

    sampler:
      name: DistributedBatchSampler
      batch_size: 32
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: True

  Eval:
    dataset: 
      name: MVTecDataset2
      dataset_path: "/home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3"
      kind: 'val'
      size: 128
      random_crop: False
      interpolation: bicubic
      aug_flip: True
      aug_rotate90: True
      aug_scaleRotate: False
      aug_brightness_contrast: True
    
    sampler:
      name: DistributedBatchSampler
      batch_size: 64
      drop_last: False
      shuffle: False
    loader:
      num_workers: 4
      use_shared_memory: True

Infer:
  infer_imgs: /home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3/2
  batch_size: 10
  transforms:
    - DecodeImage:
        to_rgb: False
        channel_first: False
    - ReCompose:
    - ResizeImage:
        resize_short: *eval_height
    - NormalizeImageTim:
        scale: 1.0/255.0
    - ToCHWImage:
  PostProcess:
    name: Topk
    topk: 1
    class_id_map_file: /home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3/label_list.txt

Metric:
  Train:
    - TopkAccTim:
        topk: [1, 2]
  Eval:
    - TopkAccTim:
        topk: [1, 2]