# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  save_interval: 20
  eval_during_train: True
  eval_interval: 1
  epochs: 120
  print_batch_step: 10
  use_visualdl: True
  
  # used for static mode and model export
  image_shape: [3, 120, 120]
  save_inference_dir: ./inference
  best_model: ./output/MobileNetV3_Mix_small_x1_25/best_model

# model architecture
Arch:
  name: MobileNetV3_Mix_small_x1_25
  class_num: 12
  input_channel: 3
  pretrained: True

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
        epsilon: 0.25
    - BCELoss:
        weight: null
  Eval:
    - CELoss:
        weight: 1.0
    - BCELoss:
        weight: null

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.13
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    coeff: 0.00002

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: MVTecDataset2
      dataset_path: "/home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3"
      kind: 'train'
      size: 120
      random_crop: False
      interpolation: bicubic
      aug_flip: True
      aug_rotate90: True
      aug_scaleRotate: False
      aug_brightness_contrast: True
      aug_rotate: True
      down_factor: 2

    sampler:
      name: DistributedBatchSampler
      batch_size: 256
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: True

  Eval:
    dataset: 
      name: MVTecDataset2
      dataset_path: "/home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3"
      kind: 'val'
      size: 120
      random_crop: False
      interpolation: bicubic
      aug_flip: True
      aug_rotate90: True
      aug_scaleRotate: False
      aug_brightness_contrast: True
      aug_rotate: True
      down_factor: 2
    
    sampler:
      name: DistributedBatchSampler
      batch_size: 128
      drop_last: False
      shuffle: False
    loader:
      num_workers: 4
      use_shared_memory: True
  
  Test1:
    dataset: 
      name: MVTecDataset2
      dataset_path: "/home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3"
      kind: 'test1'
      size: 120
      random_crop: False
      interpolation: bicubic
      aug_flip: False
      aug_rotate90: False
      aug_scaleRotate: False
      aug_brightness_contrast: False
      aug_rotate: False
      down_factor: 2

    sampler:
      name: DistributedBatchSampler
      batch_size: 256
      drop_last: False
      shuffle: False
    loader:
      num_workers: 8
      use_shared_memory: True

  Test2:
    dataset: 
      name: MVTecDataset2
      dataset_path: "/home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3"
      kind: 'test2'
      size: 120
      random_crop: False
      interpolation: bicubic
      aug_flip: False
      aug_rotate90: False
      aug_scaleRotate: False
      aug_brightness_contrast: False
      aug_rotate: False
      down_factor: 2

    sampler:
      name: DistributedBatchSampler
      batch_size: 256
      drop_last: False
      shuffle: False
    loader:
      num_workers: 8
      use_shared_memory: True

  Test3:
    dataset: 
      name: MVTecDataset2
      dataset_path: "/home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3"
      kind: 'test3'
      size: 120
      random_crop: False
      interpolation: bicubic
      aug_flip: False
      aug_rotate90: False
      aug_scaleRotate: False
      aug_brightness_contrast: False
      aug_rotate: False
      down_factor: 2

    sampler:
      name: DistributedBatchSampler
      batch_size: 256
      drop_last: False
      shuffle: False
    loader:
      num_workers: 8
      use_shared_memory: True

Infer:
  infer_imgs: /home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3/val/06_Cuoceng-
  batch_size: 10
  transforms:
    - DecodeImage:
        to_rgb: False
        channel_first: False
    - ReCompose:
    - ResizeImage:
        resize_short: 120
    - NormalizeImageTim:
        scale: 1.0/255.0
    - ToCHWImage:
  PostProcess:
    name: Topk
    topk: 1
    class_id_map_file: /home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3/label_list.txt

Metric:
  Train:
    - TopkAccTim:
        topk: [1, 2]
  Eval:
    - TopkAccTim:
        topk: [1, 2]
