eval_channel: &eval_channel 3               
dataset_path: &dataset_path "D:/AIVIS_Workspace/Data/classify/Crack_Classify/Data"  

# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu:0                             
  save_interval: 50
  eval_during_train: True
  eval_interval: 1
  epochs: 360
  print_batch_step: 10
  use_visualdl: True

  # used for static mode and model export
  image_shape: [*eval_channel, 224, 224]      
  save_inference_dir: ./inference
  best_model: ./output/MobileNetV3_Mix_small_x1_0/best_model

# model architecture
Arch:
  name: MobileNetV3_Mix_small_x1_0
  class_num: 3                              
  input_channel: *eval_channel
  pretrained: True
  use_ssld: True

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
        epsilon: 0.30
    - BCELoss:
        weight: null
  Eval:
    - CELoss:
        weight: 1.0
    - BCELoss:
        weight: null

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.13       
    warmup_epoch: 5
  regularizer:
    name: 'L2'
    coeff: 0.00002

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: MVTecDatasetSingle
      dataset_path: *dataset_path
      kind: 'train'
      size: 224                                                           
      random_crop: False                                                 
      interpolation: bicubic
      aug_flip: True                                                     
      aug_rotate90: True                                                 
      aug_scaleRotate: True                                             
      aug_brightness_contrast: True                                      
      down_factor: 2
      input_channel: *eval_channel

    sampler:
      name: DistributedBatchSampler
      batch_size: 64                                                    
      drop_last: False
      shuffle: True
    loader:
      num_workers: 0
      use_shared_memory: True

  Eval:
    dataset: 
      name: MVTecDatasetSingle
      dataset_path: *dataset_path
      kind: 'val'
      size: 224                                                                      
      random_crop: False
      interpolation: bicubic
      aug_flip: True
      aug_rotate90: True
      aug_scaleRotate: False
      aug_brightness_contrast: False
      down_factor: 2
      input_channel: *eval_channel
    
    sampler:
      name: DistributedBatchSampler
      batch_size: 4                                                             
      drop_last: False
      shuffle: True
    loader:
      num_workers: 0
      use_shared_memory: True


Infer:
  infer_imgs: /home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3/2
  batch_size: 10
  transforms:
    - DecodeImage:
        to_rgb: False
        channel_first: False
    - ResizeImage:
        resize_short: 96
    - NormalizeImageTim:
        scale: 1.0/255.0
    - ToCHWImage:
  PostProcess:
    name: Topk
    topk: 1
    class_id_map_file: /home/zhangss/Tim.Zhang/001_Segment/MixSegClsNet/datasets/LED-3/label_list.txt

Metric:
  Train:
    - TopkAccTim:
        topk: [1, 1]                                                        
  Eval:
    - TopkAccTim:
        topk: [1, 1]
